---
Zobowiązania krótkoterminowe: short_term_liabilities
Z tytułu dostaw i usług: short_term_deliveries_services
Kredyty i pożyczki: short_term_credit_loans
Z tytułu emisji dłużnych papierów wartościowych: short_term_debt_securities
Zobowiązania z tytułu leasingu finansowego: short_term_leasing
Inne zobowiązania krótkoterminowe: other_short_term_liabilies
